#!/bin/bash

[ $PWD != $HOME ] && echo -e "You're not in your $HOME folder" && exit 1

[ ! -f $HOME/Pkgfile.example ] && echo -e "Can not find Pkgfile.example, the template file for making a Pkgfile for your package" && exit 1

if [ -z $EDITOR ]
	then
		echo -e "\nEDITOR variable not set, please choose one between"
		echo -e "\ne3, vim and nano"
		read edit
		case $edit in
			e3|vi|vim|nano)
				echo -e "\nOk, thanks"
				edit=$(which $edit)
			;;
			*)
				echo -e "\nBad choice, aborting..."
				exit 1
			;;
		esac
	else
		edit=$(which $EDITOR)
fi

echo -e "\nIn which collection do you want to create your recipe ?\n"
echo -e "\nPossibles answers are\nbase, cli, gui, cli-extra, gui-extra"
echo -e "\nkde5, gnome, lxde, xfce4, mate, nos ?"
read collection

echo -e "\nWhat is the name of the package you want to build"
read package

case $collection in
	base)
		[ ! -d $HOME/base-sysd ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/base-sysd/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/base-sysd/$collection/$package/Pkgfile
		echo -e "Now, finalize the Pkgfile"
		sleep 3
		$edit $HOME/base-sysd/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
		echo -e "\n $HOME/base-sysd/$collection/$package/Pkgfile"
		exit 0
	;;

	cli|gui)
		[ ! -d $HOME/core ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/core/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/core/$collection/$package/Pkgfile
		echo -e "Now, finalize the Pkgfile"
                sleep 3
                $edit $HOME/core/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
                echo -e "\n $HOME/core/$collection/$package/Pkgfile"
                exit 0
	;;

	cli-extra|gui-extra)
		[ ! -d $HOME/extra ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/extra/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/extra/$collection/$package/Pkgfile
		echo -e "Now, finalize the Pkgfile"
                sleep 3
                $edit $HOME/extra/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
                echo -e "\n $HOME/extra/$collection/$package/Pkgfile"
                exit 0
	;;

	kde5|kde5-extra)
		[ ! -d $HOME/kde5 ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/kde5/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/kde5/$collection/$package/Pkgfile
		echo -e "Now, finalize the Pkgfile"
                sleep 3
                $edit $HOME/kde5/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
                echo -e "\n $HOME/kde5/$collection/$package/Pkgfile"
                exit 0
	;;

	gnome|gnome-extra)
		[ ! -d $HOME/gnome ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/gnome/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/gnome/$collection/$package/Pkgfile
		echo -e "Now, finalize the Pkgfile"
                sleep 3
                $edit $HOME/gnome/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
                echo -e "\n $HOME/gnome/$collection/$package/Pkgfile"
                exit 0
	;;

	lxde|lxde-extra)
		[ ! -d $HOME/lxde ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/lxde/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/lxde/$collection/$package/Pkgfile
		echo -e "Now, finalize the Pkgfile"
                sleep 3
                $edit $HOME/lxde/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
                echo -e "\n $HOME/lxde/$collection/$package/Pkgfile"
                exit 0
	;;

	xfce4|xfce4-extra)
		[ ! -d $HOME/xfce4 ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/xfce4/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/xfce4/$collection/$package/Pkgfile
                echo -e "Now, finalize the Pkgfile"
                sleep 3
                $edit $HOME/xfce4/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
                echo -e "\n $HOME/xfce4/$collection/$package/Pkgfile"
                exit 0
	;;

	mate|mate-extra)
		[ ! -d $HOME/mate ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/mate/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/mate/$collection/$package/Pkgfile
                echo -e "Now, finalize the Pkgfile"
                sleep 3
                $edit $HOME/mate/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
                echo -e "\n $HOME/mate/$collection/$package/Pkgfile"
                exit 0
	;;

	nos)
		[ ! -d $HOME/nos ] && echo -e "\nYour local git repo is not at the right place or\nyou don't make the git clone before starting the script" && exit 1
		mkdir -pv $HOME/nos/$collection/$package/
		cat $HOME/Pkgfile.example > $HOME/nos/$collection/$package/Pkgfile
		echo -e "Now, finalize the Pkgfile"
                sleep 3
                $edit $HOME/nos/$collection/$package/Pkgfile
		echo -e "\nYou'll found your Pkgfile here"
                echo -e "\n $HOME/nos/$collection/$package/Pkgfile"
                exit 0
	;;

	*)
		echo -e "This collection $collection does not exist, aborting..." && exit 1
	;;
esac
